### ISSUE TITLE
ability to change between the normal webscraper(1.4.4 and below) and the advanced one(1.5.0)

### ISSUE THREAD

**Issue by ThonkPT** [CrypticShy/vapor-store#12]
title says it all, just because its way easier to add the only working repo if this was implemented atleast for newer users like me

**Comment by ThonkPT** [comment]
i had to have a dude in another issue tell me about the discord thing just because i wasnt able to find it after two hours of google

**Comment by CrypticShy** [comment]
There is a good reason I changed to a more advanced webscraper, currrently no plans for a easy webscraper
