### ISSUE TITLE
Multiple Downloads changes preview of first downloaded item 

### ISSUE THREAD

**Issue by Nomad227** [CrypticShy/vapor-store#4]
If you attempt to download 2+ things, when the first download will completes it will use the metadata of the most previous download attempt. 

This image shows the preview as Receiver, but will actually launch Amid Evil.
![This image shows the preview as Receiver, but will actually launch Amid Evil.](https://user-images.githubusercontent.com/37667048/83075941-88f3be00-a029-11ea-9546-729d327c8b07.png)

**Comment by CrypticShy** [comment]
There is some issues with metadata but it's not an issue with the downloader, if you try to start another download whilst already downloading you will get a popup saying "Already downloading" and will cancel the download you wanted to start
