### ISSUE TITLE
Invisible button

### ISSUE THREAD

**Issue by fabiotp91** [CrypticShy/vapor-store#8]
Vapor Store version 1.4.1

I don't know if this has a function because when I click it nothing happens, but there's an invisible button on top of "Settings" that does nothing.

![Vapor_Store_E8qct8PLyI](https://user-images.githubusercontent.com/2072484/83130735-4afca580-a0ce-11ea-8c0b-33a24461901a.png)

**Comment by VanderPants2** [comment]
It's your progress bar for when you are downloading games.
![image](https://user-images.githubusercontent.com/57048338/83135570-4ba13600-a0e6-11ea-8017-33db1f4ec569.png)

**Comment by CrypticShy** [comment]
Correct
